Change symbol type from hash to string in contract
bandprotocol/band-std-reference-contracts-ink pull request #7
Opened 2024-01-16 09:39 UTC by satawatnack

2024-01-16 12:40 UTC, taobun requested changes

2024-01-16 12:40 UTC, taobun commented on contracts/std_ref/lib.rs
> +        /// Mapping from String of symbol to price datum
Fix comment

2024-01-16 12:40 UTC, taobun commented on contracts/std_ref/lib.rs
> +                .unwrap_or_else(|err| panic!("Failed to set code String due to {:?}", err));
fix to hash please

2024-01-18 05:29 UTC, RogerKSI commented on contracts/std_ref/lib.rs
> +        // Mapping from String of symbol to price datum
```suggestion
        // Mapping from string of symbol to price datum
```

2024-01-18 08:55 UTC, RogerKSI approved these changes

2024-01-18 08:57 UTC, RogerKSI approved these changes

2024-01-18 09:28 UTC, RogerKSI approved these changes

2024-01-19 02:55 UTC, taobun commented on contracts/std_ref/lib.rs
> +        /// Mapping from string of symbol to price datum
Mapping from symbol to ...

2024-01-22 13:38 UTC, taobun commented on contracts/std_ref/lib.rs
> +            symbol_pair: Vec<(String, String)>,
Should we change to symbol_pairs?

2024-01-22 17:15 UTC, taobun commented on contracts/std_ref/lib.rs
> +            symbol_pairs: (String, String),
Use symbol_pair for 1 pair

2024-01-23 05:53 UTC, taobun approved these changes

2024-01-23 05:53 UTC, merged